### ISSUE TITLE
Use Github Pages for hosting.

### ISSUE THREAD

**Issue by sdroadie** [BmoreBlackTechies/BmoreBlackTechies.github.io#5]
Since this is currently a static site, we should be able to use Github Pages to host this. We can get the domain bmoreblacktechies.github.io for free, and it'll also be behind https, which is important.

I'm not sure if we *need* to be using a static site generator like Jekyll to leverage this.

**Comment by mrwhiterk** [comment]
I don't think so. On my repos I just go to setting and it generates the github pages and URL for me.

**Comment by jocures** [comment]
I think that this works for now! Im closing this issue unless others have objections.
